GB LVL2 Homework3
alvidediev/GBHomeworks pull request #11
Opened 2022-01-13 17:39 UTC by alvidediev

Когда слушаю Ваши лекции все кажется легким, а когда дело доходит до реализации, то уже все... Но как говорится глаза боятся - руки делают. Гуглил много, так что возможно не саааааааааамое лучшее решение. Жду критик :)

2022-01-15 09:14 UTC, efserg requested changes
А где же подсчет слов? :(

2022-01-15 09:14 UTC, efserg commented on GBHomework1/src/main/java/GBLVL2/Homework3/PhoneBook.java
> +    Map<String, List<String>> hashMap = new HashMap<>();
Поле должно быть приватным

2022-01-15 09:14 UTC, efserg commented on GBHomework1/src/main/java/GBLVL2/Homework3/PhoneBook.java
> +    List<String> phoneNumbersList;
Пусть лучше это будет переменной внутри метода, объявлять ее на уровне класса нет никакого смысла

2022-01-15 09:14 UTC, efserg commented on GBHomework1/src/main/java/GBLVL2/Homework3/PhoneBook.java
> +        }else
Тот случай, когда фигурные скобки `{}` для else реально нужны

2022-01-15 11:30 UTC, alvidediev reviewed
Изменения

2022-01-15 16:23 UTC, efserg approved these changes

2022-01-15 16:23 UTC, efserg commented on GBHomework1/src/main/java/GBLVL2/Homework3/UniqueWords.java
> +            System.out.println(key + ": " + Collections.frequency(listOfWords, key) + " раза.");
Самое очевидное решение не всегда является самым оптимальным ;)

2022-01-17 08:30 UTC, alvidediev commented on GBHomework1/src/main/java/GBLVL2/Homework3/UniqueWords.java
> +            System.out.println(key + ": " + Collections.frequency(listOfWords, key) + " раза.");
> Самое очевидное решение не всегда является самым оптимальным ;)

Вы, наверное, 100% знали, что я воспользуюсь методом .frequency :D

2022-01-17 10:23 UTC, merged