Gblvl2 homework5
alvidediev/GBHomeworks pull request #12
Opened 2022-01-21 11:08 UTC by alvidediev

Не понял, почему мои потоки не синхронизировались после указания в методе модификатора synchronized

2022-01-22 08:32 UTC, efserg requested changes

2022-01-22 08:32 UTC, efserg commented on GBHomework1/src/main/java/GBLVL2/Homework5/ThreadLesson.java
> +        thread2.start();
А где же join?
Так нечестно

2022-01-22 10:18 UTC, alvidediev reviewed
Добавил join'ы :)

2022-01-23 07:44 UTC, efserg requested changes

2022-01-23 07:44 UTC, efserg commented on GBHomework1/src/main/java/GBLVL2/Homework5/ThreadLesson.java
> +            thread1.join();
Все равно неверно. Теперь программа работает так - запускается первый тред, ждем завершения (join - блокирующая операция, текущий поток останавливается до завершения работы треда), запускаем второй тред - ждем завершения. Фактически получается, что треды работают последовательно, а не параллельно.
Надо сначала запустить оба потока, а потом уже вызвать join у обоих
```
thread1.start();
thread2.start();
try {
            thread1.join();
            thread2.join();
...
```

2022-01-23 11:16 UTC, alvidediev reviewed
Еще фикс :)

2022-01-23 18:23 UTC, merged