Server & Client
alvidediev/GBHomeworks pull request #13
Opened 2022-01-24 13:40 UTC by alvidediev

Знаю, что неправильное решение, но все же решил Вам показать, чтобы, так сказать, придти к правильному решению и не ждать дедлайна, как вы сказалаи)

2022-01-27 16:58 UTC, efserg requested changes
Альви, жду исправлений

2022-01-27 16:58 UTC, efserg commented on GBHomework1/src/main/java/GBLVL2/Homework6/Server.java
> +                        out.writeUTF(scanner.nextLine());
Вот это надо вынести в отдельный поток, чтобы разделить операции чтения из консоли, отправки клиенту и чтения из потока ввода. Можно даже перенести это в основной поток.
Посмотрите, как мы сделали в чате (6 урок)

2022-01-27 20:17 UTC, alvidediev reviewed
Переместил в основной поток. Что вызывает подозрения, так это то, что программа не перестает работать после /end

2022-01-29 07:02 UTC, efserg approved these changes

2022-01-29 07:51 UTC, merged